"""One-off reporting script for the 'present' phase of the EV policy comparison plan.

Reads results/results.csv (already generated by the grid-running phase) and produces:
- results/policy_comparison.png (multi-panel metric comparison)
- results/reward_by_scenario.png (box plots of total_reward per policy, faceted by scenario)
- a JSON aggregate (printed to stdout / saved to results/_agg.json) used to hand-embed
  data into the Cursor Canvas.

This script does not modify any simulation/policy/ML code; it only reads results/results.csv.
"""
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
CSV_PATH = os.path.join(RESULTS_DIR, "results.csv")

POLICIES = ["greedy", "greedy_sequential", "nearest", "random", "rl"]
SCENARIOS = ["low", "medium", "high", "congested"]
SCENARIO_LABELS = {
    "low": "Low (40 EV / 25 st.)",
    "medium": "Medium (100 EV / 20 st.)",
    "high": "High (180 EV / 15 st.)",
    "congested": "Congested (220 EV / 10 st.)",
}
POLICY_COLORS = {
    "greedy": "#4C72B0",
    "greedy_sequential": "#55A868",
    "nearest": "#C44E52",
    "random": "#8172B2",
    "rl": "#CCB974",
}

METRICS = [
    ("average_wait_time", "Average Wait Time (s)"),
    ("average_travel_distance_km", "Average Travel Distance (km)"),
    ("avg_queue_length", "Average Queue Length (vehicles)"),
    ("max_queue_length", "Max Queue Length (vehicles)"),
    ("avg_station_utilization", "Avg Station Utilization (fraction)"),
    ("throughput_per_hour", "Throughput (vehicles/hour)"),
    ("completion_rate", "Completion Rate (fraction)"),
    ("total_reward", "Total Reward (higher = better)"),
]


def main():
    df = pd.read_csv(CSV_PATH)
    df["scenario"] = pd.Categorical(df["scenario"], categories=SCENARIOS, ordered=True)
    df["policy"] = pd.Categorical(df["policy"], categories=POLICIES, ordered=True)

    # ---- Multi-panel grouped bar chart: mean of each metric, policy x scenario ----
    fig, axes = plt.subplots(4, 2, figsize=(15, 20))
    axes = axes.flatten()
    bar_width = 0.15
    x = np.arange(len(SCENARIOS))

    for ax, (col, ylabel) in zip(axes, METRICS):
        means = df.groupby(["scenario", "policy"], observed=True)[col].mean().unstack()
        for i, policy in enumerate(POLICIES):
            vals = means[policy].values if policy in means.columns else np.zeros(len(SCENARIOS))
            ax.bar(x + (i - 2) * bar_width, vals, width=bar_width, label=policy,
                   color=POLICY_COLORS[policy])
        ax.set_xticks(x)
        ax.set_xticklabels([SCENARIO_LABELS[s] for s in SCENARIOS], rotation=15, ha="right", fontsize=8)
        ax.set_ylabel(ylabel, fontsize=9)
        ax.set_title(ylabel, fontsize=10, fontweight="bold")
        ax.grid(axis="y", alpha=0.3)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=5, bbox_to_anchor=(0.5, 1.0), fontsize=10)
    fig.suptitle(
        "EV Charging Policy Comparison Across Traffic Densities\n"
        "(mean over 20 seeds per policy x scenario cell, seeds 100-119)",
        fontsize=13, fontweight="bold", y=1.03,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    out1 = os.path.join(RESULTS_DIR, "policy_comparison.png")
    fig.savefig(out1, dpi=140, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {out1}")

    # ---- Box plots of total_reward per policy, faceted by scenario ----
    fig2, axes2 = plt.subplots(1, 4, figsize=(20, 5), sharey=False)
    for ax, scenario in zip(axes2, SCENARIOS):
        sub = df[df["scenario"] == scenario]
        data = [sub[sub["policy"] == p]["total_reward"].values for p in POLICIES]
        bp = ax.boxplot(data, labels=POLICIES, patch_artist=True)
        for patch, policy in zip(bp["boxes"], POLICIES):
            patch.set_facecolor(POLICY_COLORS[policy])
            patch.set_alpha(0.7)
        ax.set_title(SCENARIO_LABELS[scenario], fontsize=10, fontweight="bold")
        ax.set_ylabel("Total Reward (higher = better)", fontsize=9)
        ax.tick_params(axis="x", rotation=30, labelsize=8)
        ax.grid(axis="y", alpha=0.3)
    fig2.suptitle(
        "Total Reward Distribution by Policy, Faceted by Traffic Density (n=20 seeds each)",
        fontsize=13, fontweight="bold",
    )
    fig2.tight_layout(rect=[0, 0, 1, 0.94])
    out2 = os.path.join(RESULTS_DIR, "reward_by_scenario.png")
    fig2.savefig(out2, dpi=140, bbox_inches="tight")
    plt.close(fig2)
    print(f"Saved {out2}")

    # ---- Completion rate + vehicles served focused chart ----
    fig3, axes3 = plt.subplots(1, 2, figsize=(14, 5))
    for col, ax, ylabel in [
        ("completion_rate", axes3[0], "Completion Rate (fraction of EVs fully charged)"),
        ("vehicles_served", axes3[1], "Vehicles Served (count)"),
    ]:
        means = df.groupby(["scenario", "policy"], observed=True)[col].mean().unstack()
        for i, policy in enumerate(POLICIES):
            vals = means[policy].values if policy in means.columns else np.zeros(len(SCENARIOS))
            ax.bar(x + (i - 2) * bar_width, vals, width=bar_width, label=policy,
                   color=POLICY_COLORS[policy])
        ax.set_xticks(x)
        ax.set_xticklabels([SCENARIO_LABELS[s] for s in SCENARIOS], rotation=15, ha="right", fontsize=8)
        ax.set_ylabel(ylabel, fontsize=9)
        ax.set_title(ylabel, fontsize=10, fontweight="bold")
        ax.grid(axis="y", alpha=0.3)
    axes3[0].legend(fontsize=8, loc="lower left")
    fig3.suptitle("Service Outcomes by Policy and Traffic Density", fontsize=13, fontweight="bold")
    fig3.tight_layout(rect=[0, 0, 1, 0.94])
    out3 = os.path.join(RESULTS_DIR, "service_outcomes.png")
    fig3.savefig(out3, dpi=140, bbox_inches="tight")
    plt.close(fig3)
    print(f"Saved {out3}")

    # ---- Aggregate JSON for canvas embedding + markdown tables ----
    agg_cols = [
        "average_wait_time", "average_travel_distance_km", "total_travel_distance_km",
        "avg_queue_length", "max_queue_length", "avg_station_utilization",
        "throughput_per_hour", "vehicles_served", "completion_rate", "abandoned_rate",
        "total_reward", "average_charging_completion_time",
    ]
    agg = df.groupby(["scenario", "policy"], observed=True)[agg_cols].mean().round(3)
    std_reward = df.groupby(["scenario", "policy"], observed=True)["total_reward"].std().round(1)

    records = []
    for (scenario, policy), row in agg.iterrows():
        rec = {"scenario": str(scenario), "policy": str(policy)}
        rec.update({k: (None if pd.isna(v) else float(v)) for k, v in row.items()})
        rec["total_reward_std"] = float(std_reward.loc[(scenario, policy)]) if not pd.isna(std_reward.loc[(scenario, policy)]) else 0.0
        records.append(rec)

    agg_path = os.path.join(RESULTS_DIR, "_agg.json")
    with open(agg_path, "w") as f:
        json.dump(records, f, indent=2)
    print(f"Saved {agg_path}")

    # Print markdown tables to stdout for easy copy into comparison_summary.md
    print("\n=== MARKDOWN TABLES ===\n")
    for scenario in SCENARIOS:
        sub = agg.xs(scenario, level="scenario")
        print(f"### {SCENARIO_LABELS[scenario]}\n")
        cols_to_show = [
            "total_reward", "completion_rate", "average_wait_time",
            "average_travel_distance_km", "avg_queue_length", "max_queue_length",
            "avg_station_utilization", "throughput_per_hour", "vehicles_served",
        ]
        header = "| Policy | " + " | ".join(cols_to_show) + " |"
        sep = "|---" * (len(cols_to_show) + 1) + "|"
        print(header)
        print(sep)
        for policy in POLICIES:
            if policy not in sub.index:
                continue
            vals = sub.loc[policy, cols_to_show]
            print(f"| {policy} | " + " | ".join(f"{v:.2f}" if isinstance(v, float) else str(v) for v in vals) + " |")
        print()


if __name__ == "__main__":
    main()
